# Generated by Django 4.2.6 on 2023-11-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
