# Generated by Django 4.2.6 on 2023-11-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_alter_profile_pn_alter_profile_rn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myimg',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
    ]
