# Generated by Django 4.2.6 on 2023-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_rename_myimg_profile_my_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='my_img',
            new_name='my_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='my_resume',
            field=models.FileField(null=True, upload_to='doc\\'),
        ),
    ]
