# Generated by Django 4.2.6 on 2023-11-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_rename_my_img_profile_my_image_profile_my_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
